# Generated by Django 4.1.7 on 2023-04-06 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
