# Generated by Django 4.1.7 on 2023-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_is_admin_account_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_dm",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is a Dungeon Master.",
                verbose_name="Dungeon Master",
            ),
        ),
    ]
