# Generated by Django 4.1.7 on 2023-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dm", "0002_alter_encounter_region_delete_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="region",
        ),
        migrations.AddField(
            model_name="encounter",
            name="region",
            field=models.ManyToManyField(blank=True, null=True, to="dm.region"),
        ),
    ]
