# Generated by Django 4.1.7 on 2023-07-13 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dm", "0003_region_remove_encounter_region_encounter_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encounter",
            old_name="region",
            new_name="regions",
        ),
    ]
