# Generated by Django 4.1.7 on 2023-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dm", "0004_rename_region_encounter_regions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="encounters", to="dm.region"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
