# Generated by Django 4.1.7 on 2023-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dm", "0005_alter_encounter_regions_alter_region_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True, related_name="scenery", to="dm.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenery",
                "verbose_name_plural": "Scenery",
                "ordering": ["name"],
            },
        ),
    ]
