# Generated by Django 4.1.7 on 2023-07-13 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="character",
            unique_together=set(),
        ),
    ]
